# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-24 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_type',
            field=models.IntegerField(choices=[(1, '员工'), (2, '老板')], default=1),
        ),
    ]
